---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

maas_keys:
  url: "https://monitoring.api.rackspacecloud.com/pki/agent/linux.asc"
  state: "present"

maas_repos:
  repo: "deb http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-{{ ansible_distribution_version | lower }}-x86_64 cloudmonitoring main"
  redhat_repo: "http://stable.packages.cloudmonitoring.rackspace.com/redhat-{{ ansible_distribution_major_version | lower }}-x86_64/" 
  state: "present"
  enabled: "yes"

maas_requires_pip_packages:
  - virtualenv

maas_pip_container_packages:
  - lxc-python2

maas_pip_packages:
  - apache-libcloud
  - cryptography
  - ipaddr
  - lxml
  - monitorstack
  - psutil
  - rackspace-monitoring-cli
  - requests

## PIP for maas
# Path to pip download/installation script.
maas_pip_upstream_url: https://bootstrap.pypa.io/get-pip.py

# Validate Certificates when downloading pip. May be set to "no" when proxy server
# is intercepting the certificates.
maas_pip_validate_certs: true

# Additional options that you might want to pass to "get-pip.py" when installing pip.
# Default `pip_get_pip_options` is an empty string.
maas_pip_get_pip_options: ""
maas_pip_source_install_options: ""

# This list var can be used to specify specific versions of pip, setuptools,
# wheel and any other packages which must be installed when pip installs.
maas_pip_install_packages:
  - pip
  - setuptools
  - wheel

#
# Distro packages to be installed for the maas-agent runtime
#
maas_agent_distro_packages:
  - python-virtualenv
