---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: neutron_all
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - include: "common-tasks/maas_excluded_regex.yml"
    - include: "common-tasks/maas_get_openrc.yml"
    - name: Set the current group
      set_fact:
        maas_current_group: neutron_all

  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  post_tasks:
    - name: Install neutron pip packages to venv
      pip:
        name: "{{ maas_openstack_neutron_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron
  hosts: neutron_server
  gather_facts: false
  tasks:
    - name: Install neutron server checks
      template:
        src: "templates/rax-maas/neutron_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install neutron lb checks
      template:
        src: "templates/rax-maas/lb_api_check_neutron.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_neutron.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled
      notify:
        - Restart rax-maas

    - name: Install neutron private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_neutron.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_neutron.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron dhcp agent
  hosts: neutron_dhcp_agent
  gather_facts: false
  tasks:
    - name: Install neutron dhcp agent checks
      template:
        src: "templates/rax-maas/neutron_dhcp_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_dhcp_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron l3 agent
  hosts: neutron_l3_agent
  gather_facts: false
  tasks:
    - name: Install neutron l3 agent checks
      template:
        src: "templates/rax-maas/neutron_l3_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_l3_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron linux bridge agent
  hosts: neutron_linuxbridge_agent
  gather_facts: false
  tasks:
    - name: Install neutron linux bridge agent checks
      template:
        src: "templates/rax-maas/neutron_linuxbridge_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_linuxbridge_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: neutron_plugin_type is not defined or not (neutron_plugin_type | search("ovs"))  
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron
    
- name: Install checks for openstack neutron OVS agent
  hosts: neutron_openvswitch_agent
  gather_facts: false
  tasks:
    - name: Install neutron OVS agent checks
      template:
        src: "templates/rax-maas/neutron_ovs_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_ovs_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: neutron_plugin_type | search("ovs")  
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron metadata agent
  hosts: neutron_metadata_agent
  gather_facts: false
  tasks:
    - name: Install neutron metadata agent checks
      template:
        src: "templates/rax-maas/neutron_metadata_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_metadata_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

- name: Install checks for openstack neutron metering agent
  hosts: neutron_metering_agent
  gather_facts: false
  tasks:
    - name: Install neutron metadata agent checks
      template:
        src: "templates/rax-maas/neutron_metering_agent_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/neutron_metering_agent_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-neutron

# NOTE(cloudnull): When we get to ONLY using Ansible 2.2+ this playbook can be removed as the handler
#                  will be globally unified.
- include: maas-restart.yml
