---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: hummingbird:hummingbird-admin
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - include: "common-tasks/maas_excluded_regex.yml"
    - name: Set the current group
      set_fact:
        maas_current_group: hummingbird

  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  post_tasks:
    - name: Install swift pip packages to venv
      pip:
        name: "{{ maas_openstack_swift_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird

- name: Install checks for hummingbird account
  hosts: hummingbird
  gather_facts: false
  tasks:
    - name: Install hummingbird account server checks
      template:
        src: "templates/rax-maas/hummingbird_account_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_account_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install hummingbird account process checks
      template:
        src: "templates/rax-maas/hummingbird_account_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_account_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird

- name: Install checks for hummingbird container
  hosts: hummingbird
  gather_facts: false
  tasks:
    - name: Install hummingbird server checks
      template:
        src: "templates/rax-maas/hummingbird_container_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_container_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install hummingbird container process checks
      template:
        src: "templates/rax-maas/hummingbird_container_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_container_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird

- name: Install checks for hummingbird object
  hosts: hummingbird
  gather_facts: false
  tasks:
    - name: Install hummingbird container server checks
      template:
        src: "templates/rax-maas/hummingbird_object_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_object_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install hummingbird container process checks
      template:
        src: "templates/rax-maas/hummingbird_object_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_object_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird

- name: Install checks for hummingbird proxy
  hosts: hummingbird
  gather_facts: false
  tasks:
    - name: Install hummingbird proxy server checks
      template:
        src: "templates/rax-maas/hummingbird_proxy_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_proxy_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird

- name: Install accesscheck for hummingbird
  hosts: hummingbird-admin
  gather_facts: false
  tasks:
    - name: Create keystone user for hummingbird filecheck
      shell: |
        source /root/openrc
        if ! {{ maas_venv_bin }}/openstack user show "{{ maas_hummingbird_accesscheck_user_name }}"; then
          if ! {{ maas_venv_bin }}/openstack project show "{{ maas_hummingbird_service_project_name }}"; then
            {{ maas_venv_bin }}/openstack project create \
                                          --domain default \
                                          --description "Service Project" \
                                          {{ maas_hummingbird_service_project_name }}
          fi
          if ! {{ maas_venv_bin }}/openstack role show "{{ maas_hummingbird_operator_role }}"; then
            {{ maas_venv_bin }}/openstack role create \
                                          {{ maas_hummingbird_operator_role }}
          fi
          MAAS_ID=$({{ maas_venv_bin }}/openstack user create \
                                                  --domain default \
                                                  --password "{{ maas_hummingbird_accesscheck_password }}" \
                                                  "{{ maas_hummingbird_accesscheck_user_name }}" | grep -w id | awk '{print $4}')
          sleep 1
          {{ maas_venv_bin }}/openstack role add \
                                        --project admin \
                                        --user "${MAAS_ID}" \
                                        "{{ maas_hummingbird_operator_role }}"
          exit 3
        fi
      args:
        executable: "/bin/bash"
      changed_when:
        - mon_user.rc == 3
      failed_when:
        - mon_user.rc not in [0, 3]
      register: mon_user
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_hummingbird_accesscheck_enabled | bool
        - inventory_hostname in groups['hummingbird-admin'][0]

    # Copy test HTML file to the hummingbird proxy for uploading
    - name: Create index file
      copy:
        src: "files/rax-maas/index.html"
        dest: "/tmp/index.html"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_hummingbird_accesscheck_enabled | bool
        - inventory_hostname in groups['hummingbird-admin'][0]

    # Place an HTML file in a hummingbird container
    - name: Setup hummingbird container monitoring check
      shell: |
        source /root/openrc;
        {{ maas_venv_bin }}/swift upload \
          --object-name index.html \
          {{ maas_hummingbird_accesscheck_container }} \
          /tmp/index.html;
        {{ maas_venv_bin }}/swift post \
          -r '.r:*' {{ maas_hummingbird_accesscheck_container }};
        {{ maas_venv_bin }}/swift post \
          -m 'web-index:index.html' \
          {{ maas_hummingbird_accesscheck_container }};
      args:
        executable: "/bin/bash"
      changed_when: false
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_hummingbird_accesscheck_enabled | bool
        - inventory_hostname in groups['hummingbird-admin'][0]

  post_tasks:
    # Fetch the hummingbird account token to build the URL
    - name: Retrieve check file key
      shell: |
        source /root/openrc;
        {{ maas_venv_bin }}/swift stat \
          {{ maas_hummingbird_accesscheck_container }} \
          index.html | grep "Account:" | awk '{print $2}';
      args:
        executable: "/bin/bash"
      register: hummingbird_url_key
      changed_when: false
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_hummingbird_accesscheck_enabled | bool
        - inventory_hostname in groups['hummingbird-admin'][0]

    # Set the full check URL as a fact
    - name: Set URL fact
      set_fact:
        maas_hummingbird_access_url_key: "{{ hummingbird_url_key.stdout }}"
      when:
        - maas_hummingbird_access_url_key is undefined
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_hummingbird_accesscheck_enabled | bool

    - name: Install hummingbird lb health checks
      template:
        src: "templates/rax-maas/lb_api_check_hummingbird_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_hummingbird_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - maas_remote_check | bool
        - maas_hummingbird_lbhealthcheck_enabled | bool
        - not maas_private_monitoring_enabled

    - name: Install hummingbird lb access checks
      template:
        src: "templates/rax-maas/lb_api_check_hummingbird_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_hummingbird_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - maas_remote_check | bool
        - maas_hummingbird_accesscheck_enabled | bool
        - not maas_private_monitoring_enabled

    - name: Install hummingbird private lb health checks
      template:
        src: "templates/rax-maas/hummingbird_lb_api_check_hummingbird_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_hummingbird_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

    - name: Install hummingbird private lb access checks
      template:
        src: "templates/rax-maas/private_lb_api_check_hummingbird_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_hummingbird_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
        - maas_hummingbird_accesscheck_enabled | bool

    - name: Install hummingbird transaction checks
      template:
        src: "templates/rax-maas/hummingbird_transaction.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/hummingbird_transaction--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
        - maas_hummingbird_transactioncheck_enabled | bool

  vars_files:
    - vars/main.yml
    - vars/maas-hummingbird.yml
  tags:
    - maas-hummingbird
