---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather swift host groups extra facts
  hosts: swift_all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Set Storage address fact for host
      set_fact:
        storage_bridge: "{{ 'ansible_' + swift.storage_network | replace('-', '_') }}"
      register: swift_storage_bridge
      when:
        - not (ansible_local['maas']['general']['deploy_osp'] | bool)
        - swift is defined
        - swift.storage_network is defined
        - inventory_hostname in groups['swift_hosts']

    - name: Set Storage_address fact for host, learned
      set_fact:
        storage_address: "{{ hostvars[inventory_hostname][storage_bridge]['ipv4']['address'] }}"
      register: swift_storage_bridge_fact
      when:
        - not (ansible_local['maas']['general']['deploy_osp'] | bool)
        - not swift_storage_bridge | skipped
        - "'ipv4' in hostvars[inventory_hostname][storage_bridge]"

    - name: Set Storage_address fact for host, default
      set_fact:
        storage_address: "{{ container_address }}"
      when:
        - not (ansible_local['maas']['general']['deploy_osp'] | bool)
        - swift_storage_bridge | skipped
        - swift_storage_bridge_fact | skipped

    - name: Set Storage_address fact for host for osp on swift proxy nodes
      set_fact:
        storage_address: "{{ storage_ip }}"
        openstack_release: ""
        swift_recon_path: "/bin"
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool
        - inventory_hostname in groups['swift_proxy']

    - name: Set Storage_address fact for host for osp swift host/storage nodes
      set_fact:
        storage_address: "{{ storage_mgmt_ip }}"
        openstack_release: ""
        swift_recon_path: "/bin"
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool
        - inventory_hostname in groups['swift_hosts']

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift account
  hosts: swift_acc
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Install swift account server checks
      template:
        src: "templates/rax-maas/swift_account_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift account process checks
      template:
        src: "templates/rax-maas/swift_account_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift


- name: Install checks for openstack swift container
  hosts: swift_cont
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Install swift container process checks
      template:
        src: "templates/rax-maas/swift_container_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container server checks
      template:
        src: "templates/rax-maas/swift_container_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift object group
  hosts: swift_obj
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Install swift object server checks
      template:
        src: "templates/rax-maas/swift_object_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift object process checks
      template:
        src: "templates/rax-maas/swift_object_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift


- name: Install swift-recon checks for openstack swift proxy
  hosts: swift_proxy
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Set the swift release
      set_fact:
        swift_release: "{{ ansible_local['maas']['general']['maas_product_osa_version'] }}"

    - name: Set recon nodes fact
      set_fact:
        maas_swift_recon_nodes: "{{ (maas_swift_multi_region_proxy_nodes | length > 0) | ternary(maas_swift_multi_region_proxy_nodes, groups['swift_proxy'][0:2]) }}"
      when:
        - maas_swift_recon_nodes is undefined

    - name: Install swift account replications checks
      template:
        src: "templates/rax-maas/swift_account_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container async checks
      template:
        src: "templates/rax-maas/swift_async_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_async_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container replication checks
      template:
        src: "templates/rax-maas/swift_container_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift md5 checks
      template:
        src: "templates/rax-maas/swift_md5_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_md5_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift object replication checks
      template:
        src: "templates/rax-maas/swift_object_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift quarantine checks
      template:
        src: "templates/rax-maas/swift_quarantine_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_quarantine_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift time sync checks
      template:
        src: "templates/rax-maas/swift_time_sync_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_time_sync_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift


- name: Install accesscheck for openstack swift proxy
  hosts: swift_proxy
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  vars:
    ansible_python_interpreter: "{{ target_venv | default(maas_venv) }}/bin/python3"
  pre_tasks:

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Safety Check - Do not run on OSP
      debug:
        msg: "Swift playbooks are non-functional on OSP. Skipping..."
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Exit
      meta: end_play
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: configure swift accesscheck
      block:
        - name: Create rax_maas_accesscheck project
          os_project:
            cloud: overcloud
            interface: "{{ keystone_check_interface }}"
            state: present
            enabled: true
            domain_id: default
            name: "{{ maas_swift_service_project_name }}"
            description: MaaS Service Project
            verify: false

        - name: Create swift rax_maas_accesscheck user
          os_user:
            cloud: overcloud
            interface: "{{ keystone_check_interface }}"
            state: present
            enabled: true
            domain: default
            default_project: "{{ maas_swift_service_project_name }}"
            name: "{{ maas_swift_accesscheck_user_name }}"
            password: "{{ maas_swift_accesscheck_password }}"
            description: "User for MaaS swift accesscheck"
            verify: false
          no_log: true

        - name: Create swift rax_maas_swiftoperator role
          os_keystone_role:
            cloud: overcloud
            interface: "{{ keystone_check_interface }}"
            state: present
            name: "{{ maas_swift_operator_role }}"
            verify: false

        - name: Associate role to rax_maas_accesscheck user
          os_user_role:
            cloud: overcloud
            interface: "{{ keystone_check_interface }}"
            state: present
            project: "{{ maas_swift_service_project_name }}"
            role: "{{ maas_swift_operator_role }}"
            user: "{{ maas_swift_accesscheck_user_name }}"
            verify: false

        # Copy test HTML file to the swift proxy
        - name: Create index file
          copy:
            src: "files/rax-maas/index.html"
            dest: "/tmp/index.html"

        # NOTE(npawelek): The os_object module doesn't understand swift
        # ACLs. Use existing python-swiftclient to upload object and set
        # permissions. This also requires python-keystoneclient for auth.
        - name: Setup swift container monitoring check
          shell: |
            source /root/openrc;
            export SWIFTCLIENT_INSECURE={{ OS_API_INSECURE | default(true) }};
            {{ maas_venv_bin }}/swift upload \
            --object-name index.html \
            {{ maas_swift_accesscheck_container }} \
            /tmp/index.html;
            {{ maas_venv_bin }}/swift post \
            -r '.r:*' {{ maas_swift_accesscheck_container }};
            {{ maas_venv_bin }}/swift post \
            -m 'web-index:index.html' \
            {{ maas_swift_accesscheck_container }};
          args:
            executable: "/bin/bash"
          changed_when: false

        # Fetch the swift account token to build the URL
        - name: Retrieve check file key
          shell: |
            source /root/openrc;
            export SWIFTCLIENT_INSECURE={{ OS_API_INSECURE | default(true) }};
            {{ maas_venv_bin }}/swift stat \
            {{ maas_swift_accesscheck_container }} \
            index.html | awk '/Account:/ {print $2}';
          args:
            executable: "/bin/bash"
          register: swift_url_key
          changed_when: false

        # Set the full check URL as a fact
        - name: Set URL fact
          set_fact:
            maas_swift_access_url_key: "{{ swift_url_key.stdout }}"
          when:
            - maas_swift_access_url_key is undefined
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

  post_tasks:
    - name: Install swift proxy server checks
      template:
        src: "templates/rax-maas/swift_proxy_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_proxy_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift lb health checks
      template:
        src: "templates/rax-maas/lb_api_check_swift_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install swift lb access checks
      template:
        src: "templates/rax-maas/lb_api_check_swift_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - not maas_private_monitoring_enabled

    - name: Install swift private lb health checks
      template:
        src: "templates/rax-maas/private_lb_api_check_swift_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_swift_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

    - name: Install swift private lb access checks
      template:
        src: "templates/rax-maas/private_lb_api_check_swift_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_swift_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
        - maas_swift_accesscheck_enabled | bool

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-swift
