---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: elasticsearch_all
  gather_facts: "{{ gather_facts | default(true) }}"
  tasks:
    - include: "common-tasks/maas_excluded_regex.yml"
  tags:
    - maas-infra-elasticsearch

- name: Install checks for infra elasticsearch
  hosts: elasticsearch_all
  gather_facts: false
  tasks:
    - name: Install elasticsearch check
      template:
        src: "templates/elasticsearch_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/elasticsearch_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-infra.yml
  tags:
    - maas-infra-elasticsearch

# NOTE(cloudnull): When we get to ONLY using Ansible 2.2+ this playbook can be removed as the handler
#                  will be globally unified.
- include: maas-restart.yml
