---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Deploy maas telegraf helper
  hosts: "hosts"
  gather_facts: true
  tasks:
    - name: Create plugin dir
      file:
        path: "{{ maas_plugin_dir }}"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"

    - name: Drop MaaS telegraf output runner
      template:
        src: "files/tigkstack/maas_telegraf_format.py"
        dest: "{{ maas_plugin_dir }}/maas_telegraf_format.py"
        owner: "root"
        group: "root"
        mode: "0755"

  vars_files:
    - vars/main.yml
    - vars/maas-tigkstack.yml
  tags:
    - maas-tigkstack-telegraf

- name: Deploy telegraf
  hosts: "hosts:all_containers"
  gather_facts: true
  pre_tasks:
    - name: Check init system
      command: cat /proc/1/comm
      changed_when: false
      register: _pid1_name
      tags:
        - always

    - name: Set the name of pid1
      set_fact:
        pid1_name: "{{ _pid1_name.stdout }}"
      tags:
        - always

    - name: Gather variables for each operating system
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "vars/maas-{{ ansible_distribution | lower }}.yml"
            - "vars/maas-{{ ansible_os_family | lower }}.yml"
          skip: true
  tasks:
    - name: Add influxdata apt-keys
      apt_key:
        url: "https://repos.influxdata.com/influxdb.key"
        state: "present"

    - name: Add influxdata repo
      apt_repository:
        repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: "present"
        update_cache: yes

    - name: Update apt sources
      apt:
        update_cache: yes
        cache_valid_time: 600
      register: apt_update
      until: apt_update | success
      retries: 5
      delay: 2

    - name: Install telegraf
      apt:
        pkg: "{{ item }}"
        state: "latest"
      with_items: "{{ maas_telegraf_distro_packages }}"

    - name: Create telegraf plugin dir(s)
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - /etc/systemd/system/telegraf.service.d
        - /opt/telegraf

    - name: Return Commands for metric
      command: "{{ maas_plugin_dir }}/maas_telegraf_format.py"
      changed_when: false
      register: _telegraf_maas_commands
      when:
        - inventory_hostname in groups['hosts']

    - name: Set the telegraf maas commands
      set_fact:
        telegraf_maas_commands: "{{ telegraf_maas_commands | union(_telegraf_maas_commands.stdout_lines) }}"
      when:
        - inventory_hostname in groups['hosts']

    - name: Drop telegraf config file
      template:
        src: templates/tigkstack/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      register: telegraf_config

    - name: Set telegraf defaults
      copy:
        content: |
          USER="root"
          GROUP="root"
        dest: /etc/default/telegraf

    - name: Set telegraf defaults systemd
      copy:
        content: |
          [Service]
          User=root
        dest: /etc/systemd/system/telegraf.service.d/telegraf.conf
      when:
        - pid1_name == "systemd"

    - name: Reload systemd daemon
      command: "systemctl daemon-reload"
      changed_when: false
      when:
        - pid1_name == "systemd"

    - name: Enable and restart telegraf
      service:
        name: "telegraf"
        enabled: true
        state: restarted
      when:
        - telegraf_config | changed

  vars_files:
    - vars/main.yml
    - vars/maas-tigkstack.yml
  tags:
    - maas-tigkstack-telegraf
