---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: swift_all
  gather_facts: "{{ gather_facts | default(true) }}"
  user: "{{ ansible_user | default('root') }}"
  become: yes
  pre_tasks:
    - include_vars: vars/maas-osp.yml
      when:
        - deploy_osp  | default(False)
    - include: "common-tasks/maas_excluded_regex.yml"
    - include: "common-tasks/maas_get_openrc.yml"
    - name: Set the current group
      set_fact:
        maas_current_group: swift_all

  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Retrieve openrc file
      fetch:
        src: /root/openrc
        dest: /root/openrc
        flat: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['hosts'] }}"
      when:
        - "'hosts' in groups"

  post_tasks:
    - name: Install swift pip packages to venv
      pip:
        name: "{{ maas_openstack_swift_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Gather swift host groups extra facts
  hosts: swift_all
  gather_facts: false
  tasks:
    - name: Set Storage address fact for host
      set_fact:
        storage_bridge: "{{ 'ansible_' + swift.storage_network | replace('-', '_') }}"
      register: swift_storage_bridge
      when:
        - swift is defined
        - swift.storage_network is defined
        - inventory_hostname in groups['swift_hosts']

    - name: Set Storage_address fact for host, learned
      set_fact:
        storage_address: "{{ hostvars[inventory_hostname][storage_bridge]['ipv4']['address'] }}"
      register: swift_storage_bridge_fact
      when:
        - not swift_storage_bridge | skipped
        - "'ipv4' in hostvars[inventory_hostname][storage_bridge]"

    - name: Set Storage_address fact for host, default
      set_fact:
        storage_address: "{{ container_address }}"
      when:
        - swift_storage_bridge | skipped
        - swift_storage_bridge_fact | skipped

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift account
  hosts: swift_acc
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: yes
  tasks:
    - name: Install swift account server checks
      template:
        src: "templates/rax-maas/swift_account_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift account process checks
      template:
        src: "templates/rax-maas/swift_account_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift container
  hosts: swift_cont
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: yes
  tasks:
    - name: Install swift container server checks
      template:
        src: "templates/rax-maas/swift_container_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container process checks
      template:
        src: "templates/rax-maas/swift_container_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift object
  hosts: swift_obj
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: yes
  tasks:
    - name: Install swift container server checks
      template:
        src: "templates/rax-maas/swift_object_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container process checks
      template:
        src: "templates/rax-maas/swift_object_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install swift-recon checks for openstack swift proxy
  hosts: swift_proxy
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: yes
  tasks:
    - name: Set recon nodes fact
      set_fact:
        maas_swift_recon_nodes: "{{ (maas_swift_multi_region_proxy_nodes | length > 0) | ternary(maas_swift_multi_region_proxy_nodes, groups['swift_proxy'][0:2]) }}"
      when:
        - maas_swift_recon_nodes is undefined

    - name: Install swift account replications checks
      template:
        src: "templates/rax-maas/swift_account_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container async checks
      template:
        src: "templates/rax-maas/swift_async_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_async_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift container replication checks
      template:
        src: "templates/rax-maas/swift_container_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift md5 checks
      template:
        src: "templates/rax-maas/swift_md5_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_md5_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift object replication checks
      template:
        src: "templates/rax-maas/swift_object_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift quarantine checks
      template:
        src: "templates/rax-maas/swift_quarantine_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_quarantine_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift time sync checks
      template:
        src: "templates/rax-maas/swift_time_sync_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_time_sync_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install accesscheck for openstack swift proxy
  hosts: swift_proxy
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: yes
  tasks:
    - name: Create keystone user for swift filecheck
      shell: |
        source /root/openrc
        if ! {{ maas_venv_bin }}/openstack user show "{{ maas_swift_accesscheck_user_name }}"; then
          if ! {{ maas_venv_bin }}/openstack project show "{{ maas_swift_service_project_name }}"; then
            {{ maas_venv_bin }}/openstack project create \
                                          --domain default \
                                          --description "Service Project" \
                                          {{ maas_swift_service_project_name }}
          fi
          if ! {{ maas_venv_bin }}/openstack role show "{{ maas_swift_operator_role }}"; then
            {{ maas_venv_bin }}/openstack role create \
                                          {{ maas_swift_operator_role }}
          fi
          MAAS_ID=$({{ maas_venv_bin }}/openstack user create \
                                                  --domain default \
                                                  --password "{{ maas_swift_accesscheck_password }}" \
                                                  "{{ maas_swift_accesscheck_user_name }}" | grep -w id | awk '{print $4}')
          sleep 1
          {{ maas_venv_bin }}/openstack role add \
                                        --project admin \
                                        --user "${MAAS_ID}" \
                                        "{{ maas_swift_operator_role }}"
          exit 3
        fi
      args:
        executable: "/bin/bash"
      changed_when:
        - mon_user.rc == 3
      failed_when:
        - mon_user.rc not in [0, 3]
      register: mon_user
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Copy test HTML file to the swift proxy for uploading
    - name: Create index file
      copy:
        src: "files/rax-maas/index.html"
        dest: "/tmp/index.html"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Place an HTML file in a swift container
    - name: Setup swift container monitoring check
      shell: |
        source /root/openrc;
        {{ maas_venv_bin }}/swift upload \
          --object-name index.html \
          {{ maas_swift_accesscheck_container }} \
          /tmp/index.html;
        {{ maas_venv_bin }}/swift post \
          -r '.r:*' {{ maas_swift_accesscheck_container }};
        {{ maas_venv_bin }}/swift post \
          -m 'web-index:index.html' \
          {{ maas_swift_accesscheck_container }};
      args:
        executable: "/bin/bash"
      changed_when: false
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Fetch the swift account token to build the URL
    - name: Retrieve check file key
      shell: |
        source /root/openrc;
        {{ maas_venv_bin }}/swift stat \
          {{ maas_swift_accesscheck_container }} \
          index.html | grep "Account:" | awk '{print $2}';
      args:
        executable: "/bin/bash"
      register: swift_url_key
      changed_when: false
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

  post_tasks:
    # Set the full check URL as a fact
    - name: Set URL fact
      set_fact:
        maas_swift_access_url_key: "{{ swift_url_key.stdout }}"
      when:
        - maas_swift_access_url_key is undefined
        - (maas_private_monitoring_enabled | bool) or (maas_remote_check | bool)
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    - name: Install swift proxy server checks
      template:
        src: "templates/rax-maas/swift_proxy_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_proxy_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install swift lb health checks
      template:
        src: "templates/rax-maas/lb_api_check_swift_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install swift lb access checks
      template:
        src: "templates/rax-maas/lb_api_check_swift_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - not maas_private_monitoring_enabled

    - name: Install swift private lb health checks
      template:
        src: "templates/rax-maas/private_lb_api_check_swift_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_swift_healthcheck--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

    - name: Install swift private lb access checks
      template:
        src: "templates/rax-maas/private_lb_api_check_swift_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_swift_access--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
        - maas_swift_accesscheck_enabled | bool

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift
