---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: "{{ designate_hosts_all|default('designate_all') }}"
  user: "{{ designate_ansible_user|default('root') }}"
  become: "{{ designate_ansible_become|default('no') }}"
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - include: "common-tasks/maas_excluded_regex.yml"
    - include: "common-tasks/maas_get_openrc.yml"
      when: not deploy_osp|default(false)
    - name: Set the current group
      set_fact:
        maas_current_group: designate_all

  tasks:
    - name: Set physical host
      set_fact:
        physical_host: "{{ ansible_host }}"
      when: deploy_osp|default(false)

    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  post_tasks:
    - name: Install designate pip packages to venv
      pip:
        name: "{{ maas_openstack_designate_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - "{{ designate_var_files|default('vars/maas-openstack.yml') }}"
  tags:
    - maas-openstack-designate

- name: Install checks for openstack designate
  hosts: "{{ designate_hosts_all|default('designate_all') }}"
  user: "{{ designate_ansible_user|default('root') }}"
  become: "{{ designate_ansible_become|default('no') }}"
  gather_facts: false
  tasks:
    - name: Set physical host
      set_fact:
        physical_host: "{{ ansible_host }}"
        internal_ips: "{{ ansible_all_ipv4_addresses|ipaddr(osp_internal_netmask)|difference([internal_vip_address]) }}"
      when: deploy_osp|default(false)

    - name: Set internal ip
      set_fact:
        internal_ip: "{{ internal_ips[0] }}"
      when: deploy_osp|default(false)

    - name: Install designate api checks
      template:
        src: "templates/rax-maas/designate_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/designate_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install designate mdns checks
      template:
        src: "templates/rax-maas/designate_mdns_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/designate_mdns_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install designate lb checks
      template:
        src: "templates/rax-maas/lb_api_check_designate.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_designate.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install designate private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_designate.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_designate.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined
  vars_files:
    - vars/main.yml
    - "{{ designate_var_files|default('vars/maas-openstack.yml') }}"
  tags:
    - maas-openstack-designate