---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: rabbitmq_all
  gather_facts: true
  become: true
  tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  tags:
    - always


- name: Gather facts
  hosts: rabbitmq_all
  gather_facts: true
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Install rabbitmq pip packages
      package:
        name: "{{ maas_rabbitmq_distro_packages }}"
        state: "present"
      register: install_pip_packages
      until: install_pip_packages is success
      retries: 5
      delay: 2

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - "vars/maas-{{ ansible_distribution | lower }}.yml"

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-infra-rabbitmq


- name: Add admin user on rabbitmq
  hosts: rabbitmq_all
  gather_facts: true
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Ensure MaaS rabbitmq user as administrator with rabbitmqctl
      rabbitmq_user:
        user: "{{ maas_rabbitmq_user }}"
        password: "{{ maas_rabbitmq_password }}"
        vhost: "/"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
        tags: "administrator"
        state: "present"
      no_log: True
      when:
        - inventory_hostname in groups['rabbitmq_all'][0]
        - not (ansible_local['maas']['general']['deploy_osp'] | bool)

    - name: Find rabbitmq docker container
      raw: /bin/docker ps -a -f status=running | awk '/rabbitmq/ {print $NF}'
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool
      register: rabbitmq_container_name

    - name: Enable rabbitmq management plugin
      command: >
        /bin/docker exec {{ rabbitmq_container_name.stdout | trim }} /bin/bash -c
        '/usr/sbin/rabbitmq-plugins enable rabbitmq_management'
      when:
        - ansible_local['maas']['general']['deploy_osp'] | bool

    - name: Ensure MaaS rabbitmq user as administrator with docker exec rabbitmqctl
      command: >
        /bin/docker exec {{ rabbitmq_container_name.stdout | trim }} /bin/bash -c
        '/usr/sbin/rabbitmqctl add_user {{ maas_rabbitmq_user }} {{ maas_rabbitmq_password }};
        /usr/sbin/rabbitmqctl set_user_tags {{ maas_rabbitmq_user }} administrator;
        /usr/sbin/rabbitmqctl set_permissions -p / {{ maas_rabbitmq_user }} ".*" ".*" ".*"'
      when:
        - inventory_hostname in groups['rabbitmq_all'][0]
        - ansible_local['maas']['general']['deploy_osp'] | bool
      no_log: True

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - "vars/maas-{{ ansible_distribution | lower }}.yml"

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-infra-rabbitmq


- name: Install checks for infra rabbitmq
  hosts: rabbitmq_all
  gather_facts: true
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: introspect rabbitmq management ip
      block:
        - name: Identify rabbitmq management listening address
          shell: ss -lt | grep -c 127.0.0.1:15672
          register: rabbit_local
          delegate_to: "{{ groups['rabbitmq_all'][0] }}"
          failed_when: rabbit_local.rc >= 2

        - name: Set rabbitmq management to local address
          set_fact:
            rabbit_local_address: "127.0.0.1"
          when: rabbit_local.rc == 0

    - name: Get list of vhosts
      uri:
        url: "http://{{ rabbit_local_address | default(container_address | default('localhost')) }}:{{ rabbitmq_mgmt_port | default('15672') }}/api/vhosts"
        user: "{{ maas_rabbitmq_user }}"
        password: "{{ maas_rabbitmq_password }}"
        return_content: yes
      no_log: True
      register: vhost_list
      when:
        - inventory_hostname in groups['rabbitmq_all'][0]

    - name: Ensure MaaS rabbitmq user has access to all openstack vhosts
      uri:
        url: "http://{{ rabbit_local_address | default(container_address| default('localhost')) }}:{{ rabbitmq_mgmt_port | default('15672') }}/api/permissions/{{ item.name | urlencode | regex_replace('/','%2F') }}/{{ maas_rabbitmq_user | urlencode }}"
        user: "{{ maas_rabbitmq_user }}"
        password: "{{ maas_rabbitmq_password }}"
        method: PUT
        return_content: yes
        body: '{"configure":".*","write":".*","read":".*"}'
        body_format: json
        status_code: 200,201,204
      with_items: "{{ vhost_list.json | default([]) }}"
      no_log: True
      when:
        - inventory_hostname in groups['rabbitmq_all'][0]

  post_tasks:
    - name: Install rabbitmq checks
      template:
        src: "templates/rax-maas/rabbitmq_status.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/rabbitmq_status--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - "vars/maas-{{ ansible_distribution | lower }}.yml"

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-infra-rabbitmq
