---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: swift_all
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - name: Check for installed swift
      stat:
        path: "/openstack/venvs/swift-{{ openstack_release }}/bin"
      register: swift_dir
    - fail:
        msg: >-
          The path "/openstack/venvs/swift-{{ openstack_release }}/bin"
          must exist for these checks to run. Check the "openstack_release"
          variable is set correctly and that swift is installed on your target
          hosts before installing this monitor.
      when:
        - not swift_dir.stat.isdir is defined or not swift_dir.stat.isdir | bool

    - include: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  post_tasks:
    - name: Install swift pip packages to venv
      pip:
        name: "{{ maas_openstack_swift_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift
  hosts: swift_all
  gather_facts: false
  tasks:
    - name: Set Storage address fact for host
      set_fact:
        storage_bridge: "{{ 'ansible_' + swift.storage_network | replace('-', '_') }}"
      register: swift_storage_bridge
      when:
        - swift is defined
        - swift.storage_network is defined
        - inventory_hostname in groups['swift_hosts']

    - name: Set Storage_address fact for host, learned
      set_fact:
        storage_address: "{{ hostvars[inventory_hostname][storage_bridge]['ipv4']['address'] }}"
      register: swift_storage_bridge_fact
      when:
        - not swift_storage_bridge | skipped
        - "'ipv4' in hostvars[inventory_hostname][storage_bridge]"

    - name: Set Storage_address fact for host, default
      set_fact:
        storage_address: "{{ container_address }}"
      when:
        - swift_storage_bridge | skipped
        - swift_storage_bridge_fact | skipped

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift account
  hosts: swift_acc
  gather_facts: false
  tasks:
    - name: Install swift account server checks
      template:
        src: "templates/swift_account_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift account process checks
      template:
        src: "templates/swift_account_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_process_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift container
  hosts: swift_cont
  gather_facts: false
  tasks:
    - name: Install swift container server checks
      template:
        src: "templates/swift_container_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift container process checks
      template:
        src: "templates/swift_container_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_server_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift object
  hosts: swift_obj
  gather_facts: false
  tasks:
    - name: Install swift container server checks
      template:
        src: "templates/swift_object_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_server_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift container process checks
      template:
        src: "templates/swift_object_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_process_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift

- name: Install checks for openstack swift proxy
  hosts: swift_proxy
  gather_facts: false
  pre_tasks:
    # Add a swift user for file checking
    - name: Create a keystone user for swift filecheck
      keystone:
        command: "ensure_user"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ maas_swift_accesscheck_user_name }}"
        tenant_name: "{{ maas_swift_service_project_name }}"
        password: "{{ maas_swift_accesscheck_password }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      register: add_user
      until: add_user | success
      retries: 5
      delay: 10
      when:
        - not maas_swift_service_in_ldap | bool
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Assign the swiftoperator role to the file checking user
    - name: Add swift role to user
      keystone:
        command: "ensure_user_role"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ maas_swift_accesscheck_user_name }}"
        tenant_name: "{{ maas_swift_service_project_name }}"
        role_name: "{{ maas_swift_operator_role }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      register: add_user_role
      until: add_user_role | success
      retries: 5
      delay: 10
      when:
        - not maas_swift_service_in_ldap | bool
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Copy test HTML file to the swift proxy for uploading
    - name: Create index file
      copy:
        dest: "/tmp/index.html"
        src: "index.html"
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Place an HTML file in a swift container
    - name: Setup swift container monitoring check
      shell: |
        source /root/openrc
        /openstack/venvs/swift-{{ openstack_release }}/bin/swift upload \
                                                                 --object-name index.html \
                                                                 {{ maas_swift_accesscheck_container }} \
                                                                 /tmp/index.html
        /openstack/venvs/swift-{{ openstack_release }}/bin/swift post \
                                                                 -r '.r:*' {{ maas_swift_accesscheck_container }}
        /openstack/venvs/swift-{{ openstack_release }}/bin/swift post \
                                                                 -m 'web-index:index.html' \
                                                                 {{ maas_swift_accesscheck_container }}
      args:
        executable: "/bin/bash"
      changed_when: false
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Fetch the swift account token to build the URL
    - name: Retrieve check file key
      shell: |
        source /root/openrc;
        /openstack/venvs/swift-{{ openstack_release }}/bin/swift stat \
                                                                 {{ maas_swift_accesscheck_container }} \
                                                                 index.html | grep "Account:" | awk '{print $2}'
      args:
        executable: "/bin/bash"
      register: swift_url_key
      changed_when: false
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

    # Set the full check URL as a fact
    - name: Set URL fact
      set_fact:
        maas_swift_access_url_key: "{{ swift_url_key.stdout }}"
      when:
        - maas_swift_access_url_key is undefined
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
        - inventory_hostname in groups['swift_proxy'][0]

  tasks:
    - name: Install swift container replications checks
      template:
        src: "templates/swift_account_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_account_replication_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift container async checks
      template:
        src: "templates/swift_async_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_async_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift container replication checks
      template:
        src: "templates/swift_container_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_container_replication_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift md5 checks
      template:
        src: "templates/swift_md5_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_md5_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift object replication checks
      template:
        src: "templates/swift_object_replication_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_object_replication_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift proxy server checks
      template:
        src: "templates/swift_proxy_server_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_proxy_server_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift quarantine checks
      template:
        src: "templates/swift_quarantine_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_quarantine_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift time sync checks
      template:
        src: "templates/swift_time_sync_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/swift_time_sync_check.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install swift lb health checks
      template:
        src: "templates/lb_api_check_swift_healthcheck.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_healthcheck.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
      notify:
        - Restart rax-maas

    - name: Install swift lb access checks
      template:
        src: "templates/lb_api_check_swift_access.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_swift_access.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - maas_swift_accesscheck_enabled | bool
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-swift
