---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install checks for openstack keystone
  hosts: keystone_all
  gather_facts: true
  user: "{{ ansible_user | default('root') }}"
  become: true
  pre_tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - name: Set the current group
      set_fact:
        maas_current_group: keystone_all

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

    - name: Create keystone user for monitoring
      shell: |
        . /root/openrc
        if ! {{ maas_venv_bin }}/openstack user show "{{ maas_keystone_user }}"; then
        MAAS_ID=$({{ maas_venv_bin }}/openstack user create \
                            --domain default \
                            --password "{{ maas_keystone_password }}" \
                            "{{ maas_keystone_user }}" | grep -w id | awk '{print $4}')
        sleep 1
        {{ maas_venv_bin }}/openstack role add \
                        --project admin \
                        --user "${MAAS_ID}" \
                        admin
        exit 3
        fi
      args:
        executable: "/bin/bash"
      changed_when:
        - mon_user.rc == 3
      failed_when:
        - mon_user.rc not in [0, 3]
      register: mon_user
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      no_log: True
      when:
        - inventory_hostname in groups['keystone_all'][0]

  tasks:
    - name: Install keystone api checks
      template:
        src: "templates/rax-maas/keystone_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/keystone_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install keystone lb checks
      template:
        src: "templates/rax-maas/lb_api_check_keystone.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_keystone.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install keystone private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_keystone.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_keystone.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-keystone
