---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#- import_playbook: maas-pre-flight.yml
#  tags:
#    - maas

- import_playbook: maas-agent-all.yml
  tags:
    - maas

#- import_playbook: maas-sdk-integration.yml
#  tags:
#    - maas

#- import_playbook: maas-poller-all.yml
#  tags:
#    - maas

#- import_playbook: maas-ceph-all.yml
#  tags:
#    - maas

#- import_playbook: maas-host-all.yml
#  tags:
#    - maas

#- import_playbook: maas-infra-all.yml
#  tags:
#    - maas

# Maintainer only created lxc-python2.
# We will need to move to maybe lxc-python3 and
# rewrite the scripts if this is still needed.
#
# Keeping commented out for now.
#- import_playbook: maas-container-all.yml
#  tags:
#    - maas

- import_playbook: maas-openstack-all.yml
  tags:
    - maas

#- import_playbook: maas-remove-old-templates.yml
#  tags:
#    - maas
#
#- import_playbook: maas-restart.yml
#  tags:
#    - maas
