name: rpc-maas-pr-workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  # Global env vars used on all jobs
  REPO_URL: 'https://github.com/shannonmitchell/rpc-maas.git'
  #REPO_URL: 'https://github.com/rcbops/rpc-maas'
  OS_CLOUD: 'phobos'
  FLAVOR: 'vm-osa-aio'
  NETWORK: 'ironic'
  KEY_NAME: 'rpc-maas-runner'
  #RE_JOB_BRANCH: 'gitactiontest'
  RE_JOB_BRANCH: ${{ github.event.pull_request.head.sha }}

# Per-Job env var info:
#   RE_JOB_SCENARIO: 'Test scenarios used by rpc-maas test scripts. Values(kilo,rpco-liberty,liberty,rpco-mitaka,mitaka,newton,ocata,pike,queens,rocky,stein,train,ceph,osp13,master)'
#   RE_JOB_IMAGE:    'Image to test against. Used by rpc-maas test scripts. Values(trusty,xenial)'
#   IMAGE_USER:      'Username used to log into the associated RE_JOB_IMAGE glance image'
#   RE_JOB_ACTION:   'Test action by rpc-maas test scripts. Values(deploy,tox-test)'
#   JOB_NAME:        'Name of the job'

jobs:
  xenial-queens:
    runs-on: self-hosted
    steps:
    - name: Check out the repo on the runner's workspace
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
       
    - name: Create testing VM 
      run: |
        #!/bin/bash
        set -x
        source /home/rpc-maas-runner/openstackclient_venv/bin/activate
        openstack --os-cloud "${OS_CLOUD}" server create --flavor "${FLAVOR}" --image "Ubuntu 16.04" --network "${NETWORK}" --key-name "${KEY_NAME}" rpc-maas-xenial-queens-${{ github.run_id }}-${{ github.run_number }} --wait


    - name: Run script to kick off testing on remote machine
      run: gating/github_action_scripts/start_remote_tests.sh
      env:
        IMAGE_USER: "ubuntu"
        RE_JOB_SCENARIO: "queens"
        RE_JOB_IMAGE: "xenial"
        RE_JOB_ACTION: "deploy"
        JOB_NAME: "xenial-queens"
        PUBCLOUD_USERNAME: "${{ secrets.PUBCLOUD_USERNAME }}"
        PUBCLOUD_API_KEY: "${{ secrets.PUBCLOUD_API_KEY }}"
        PUBCLOUD_TENANT_ID: "${{ secrets.PUBCLOUD_TENANT_ID }}"

    - name: Delete testing VM
      run: |
        #!/bin/bash
        set -x
        source /home/rpc-maas-runner/openstackclient_venv/bin/activate
        openstack --os-cloud "${OS_CLOUD}" server delete rpc-maas-xenial-queens-${{ github.run_id }}-${{ github.run_number }} --wait

  bionic-train:
    runs-on: self-hosted
    steps:
    - name: Check out the repo on the runner's workspace
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
       
    - name: Create testing VM 
      run: |
        #!/bin/bash
        set -x
        source /home/rpc-maas-runner/openstackclient_venv/bin/activate
        openstack --os-cloud "${OS_CLOUD}" server create --flavor "${FLAVOR}" --image "Ubuntu 18.04" --network "${NETWORK}" --key-name "${KEY_NAME}" rpc-maas-bionic-train-${{ github.run_id }}-${{ github.run_number }} --wait


    - name: Run script to kick off testing on remote machine
      run: gating/github_action_scripts/start_remote_tests.sh
      env:
        IMAGE_USER: "ubuntu"
        RE_JOB_SCENARIO: "train"
        RE_JOB_IMAGE: "bionic"
        RE_JOB_ACTION: "deploy"
        JOB_NAME: "bionic-train"
        PUBCLOUD_USERNAME: "${{ secrets.PUBCLOUD_USERNAME }}"
        PUBCLOUD_API_KEY: "${{ secrets.PUBCLOUD_API_KEY }}"
        PUBCLOUD_TENANT_ID: "${{ secrets.PUBCLOUD_TENANT_ID }}"

    - name: Delete testing VM
      run: |
        #!/bin/bash
        set -x
        source /home/rpc-maas-runner/openstackclient_venv/bin/activate
        openstack --os-cloud "${OS_CLOUD}" server delete rpc-maas-bionic-train-${{ github.run_id }}-${{ github.run_number }} --wait

